### ISSUE TITLE
多种语言无法正确识别

### ISSUE THREAD

**Issue by jinghaifeng1** [KANLON/language-distinguish#1]
联系方式：qq 850407122
背景：游戏多语言配置表，识别语言种类与预期是否一致。配置表数据量庞大，8M文件
使用背景：我不会java，用的python 的jpype 库来调用jar包。
问题：
主要问题：
1、相当多俄语被识别成保加利亚语
2、相当多日语被识别成韩语
3、相当多繁体中文被识别为韩语、简体中文

希望作者能联系我，一起讨论下问题，感谢作者开源这么棒的接口

**Comment by KANLON** [comment]
有什么问题可以直接在issue提，有问题的识别的例子，也贴一下出来吧

**Comment by KANLON** [comment]
太久没回复，关闭了
