### ISSUE TITLE
多语种识别错乱

### ISSUE THREAD

**Issue by raintruth** [KANLON/language-distinguish#3]
String str = "Всем доброго дня 빛이나";
long l = System.currentTimeMillis();
String rst = LanguageDistinguish.getLanguageByString(str, DetectMode.PRECISION);
System.out.println(String.format("精准耗时%s >>> %s",System.currentTimeMillis() -l , rst));

long l2 = System.currentTimeMillis();
String rst2 = LanguageDistinguish.getLanguageByString(str, DetectMode.IMPRECISION);
System.out.println(String.format("模糊耗时%s >>> %s",System.currentTimeMillis() -l2 , rst2));

精准耗时364 >>> {"uk":1.00}
模糊耗时0 >>> {"uk":1.00}

**Comment by KANLON** [comment]
这个有什么问题吗？这个应该就是乌克兰语或俄语？
